### ISSUE TITLE
Please add this provider to the Terraform Registry

### ISSUE THREAD

**Issue by gnarea** [codefresh-io/terraform-provider-codefresh#18]
I think the current setup is too complicated, especially for those of us using Terraform Cloud as that makes things even more complicated we have to host the compiled provider in a private registry.

**Comment by gnarea** [comment]
Actually, I found an easier workaround: Put the compiled provider under version control (e.g., https://github.com/relaycorp/cloud-gateway/tree/main/tf-workspace/terraform.d)

But I still think registering this provider in the registry would make things easier.

**Comment by kpurdon** [comment]
@sandrogattuso @vadimgusev-codefresh having this in the terraform registry would make this much easier to adopt and start testing. It should be pretty simple to publish this as a community provider.

Any thoughts?

**Comment by sandrogattuso** [comment]
@kpurdon I'm an external contributor, unfortunately this is not something I can help with since I don't have access  to perform the required actions

**Comment by kpurdon** [comment]
@alex-codefresh @vadimgusev-codefresh what can I do to help accomplish this. We currently jumping through a bunch of hoops to install/use this. It would be amazing to get this published ASAP.

The docs: https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by vadimgusev-codefresh** [comment]
@kpurdon we need to review current state of the repo and make necessary adjustments to make it compliant with publishing requirements.

Unfortunately, it's not in our current roadmap and we will not be able to squeeze it in due to capacity limitations on our side for some time.

However, we would highly appreciate any PRs that would push this repo towards meeting publishing requirements.

**Comment by kpurdon** [comment]
Hi, @vadimgusev-codefresh do you mean some internal to Codefresh requirements? I was able to get a fork of this published w/ very minimal modifications to the goreleaser config in ~15min. https://registry.terraform.io/providers/kpurdon/codefresh/. I'm more than happy to do that, but it will require a tiny bit of repo work (adding a GPG key) and someone on the Codefresh side to set up the Terraform registry integration.

Again, this all took ~15 minutes to complete. Let me know if this is something a repo maintainer could take on. I'm more than happy to do the work, I just don't have the access.

Thanks!

**Comment by sharon-codefresh** [comment]
Codefresh provider has been successfully publish in HCP official registry:
https://registry.terraform.io/providers/codefresh-io/codefresh/latest
