### ISSUE TITLE
Support CRON trigger type for pipeline

### ISSUE THREAD

**Issue by dustinvanbuskirk** [codefresh-io/terraform-provider-codefresh#39]
Pipeline does not support CRON triggers.

We need to add this additional trigger type to support pipelines using CRON triggers.

**Comment by templarfelix** [comment]
have date 4 solve this issue?

**Comment by danielvincenzi** [comment]
What is the estimated delivery of this issue?

**Comment by sandrogattuso** [comment]
@dustinvanbuskirk is there any documentation on how this works from an API perspective? I had a look around the CRON triggers configuration and this is something that is not directly attached to the pipeline. 
From what I've understood looking at the API calls made by the browser when editing the configuration, seems you have at least another 2 API endpoints involved in the generation of the CRON trigger.

Adding the feature in the resource_pipeline would go against the recommended practices https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object

I can help on the implementation of this but I would like to know if you had any thought around how this would look like from a resource perspective in terraform.

**Comment by denis-codefresh** [comment]
From my perspective it's better to embed `trigger_cron` resource in the pipeline (make a new block).
Event if API looks different for cron and git triggers it's better to keep them at same place in your "infrastructure code".
@ziv-codefresh WDYT?

**Comment by kpurdon** [comment]
@denis-codefresh any update here? Can you make the call on a preferred design? If I were to put in the work for a trigger_cron would that be accepted?

**Comment by Laurent-OC** [comment]
@denis-codefresh any update here?

**Comment by expnch** [comment]
@denis-codefresh We are still waiting on an update.

**Comment by denis-codefresh** [comment]
@kpurdon Let's create a new trigger type block in addition to a regular `trigger` called `cron_trigger`.

**Comment by korenyoni** [comment]
Hi all. Sorry for the huge delay. We didn't really have a maintainer assigned to this repo (until now).

Basically, @denis-codefresh and I agreed that the git_trigger block should be deprecated, and standalone resources for each of our triggers should be supported:

* `codefresh_pipeline_git_trigger`
* `codefresh_pipeline_cron_trigger`
* `codefresh_pipeline_helm_trigger`
* `codefresh_pipeline_registry_trigger`.

There is some WIP stuff here in my fork https://github.com/korenyoni/terraform-provider-codefresh. We are also overhauling documentation, release automation, and probably a couple other small things we can fit into a minor release (`0.1.0`). We are expecting some turnaround on this in the next two weeks. My goal is to get this repo into better shape...

**Comment by korenyoni** [comment]
We have a [PR](https://github.com/codefresh-io/terraform-provider-codefresh/pull/90) open for this now. What I said about the other 3 types of standalone triggers is actually going to be moved out to `0.2.0`, even though it would have been ideal to release all 4 as part of `0.1.0` and deprecate the inline trigger.
