### ISSUE TITLE
darwin_arm64 not supported - Mac M1

### ISSUE THREAD

**Issue by thiagolsfortunato** [codefresh-io/terraform-provider-codefresh#76]
I didn't see an existing issue, so I thought I'd open an issue to track building an arm64 (Apple Silicon) binary for macOS.

After migrating to a new Mac, I have seen at least one issue using Terraform almost straight away:

```terraform
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/codefresh-io/codefresh v0.0.22 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
╵
```

Terraform Version:

```                    
Terraform v1.1.4
on darwin_arm64
+ provider registry.terraform.io/codefresh-io/codefresh v0.0.22
```

**Comment by xplrior** [comment]
We have released version 0.0.23 that has M1 Mac Support.

GitHub Release: [Release 0.0.23](https://github.com/codefresh-io/terraform-provider-codefresh/releases/tag/0.0.23)
Terraform: [Version 0.0.23](https://registry.terraform.io/providers/codefresh-io/codefresh/0.0.23)
