### ISSUE TITLE
Support standalone triggers

### ISSUE THREAD

**Issue by n1cholasgeorge** [codefresh-io/terraform-provider-codefresh#84]
Hi,

Is there any chance we might see support for pipeline triggers that are defined outside of the `codefresh_pipeline` block?

Being able to do something like this would be wonderful:

```
resource "codefresh_trigger" "my_trigger" {
    branch_regex  = "/.*/gi"
    context            = "git"
    description      = "Trigger for tags"
    disabled           = false
    events              = [
      "push.tags"
    ]
    modified_files_glob = ""
    commit_status_title = "tags-trigger"
    name                = "tags"
    provider            = "github"
    repo                = "codefresh-contrib/react-sample-app"
    type                = "git"
}

resource "codefresh_trigger_attachment" "my_trigger_attachment" {
    trigger_id  = codefresh_trigger.my_trigger.id
    pipeline_id = codefresh_pipeline.my_pipeline.id
}
```

Cheers

**Comment by korenyoni** [comment]
As of https://github.com/codefresh-io/terraform-provider-codefresh/issues/39#issuecomment-1246652205 standalone triggers are planned. 

However, there is no need for an attachment resource. Your proposal is probably inspired by IAM policy attachments, but really, the trigger just needs a pipeline ID and that's it.

**Comment by korenyoni** [comment]
Please see https://github.com/codefresh-io/terraform-provider-codefresh/issues/39#issuecomment-1679134189

Unfortunately the API used for these standalone triggers is being deprecated and we are moving towards inline blocks for them instead 😞
