### ISSUE TITLE
Terraform documentation, no mention of Data Source.

### ISSUE THREAD

**Issue by brunotorrente** [codefresh-io/terraform-provider-codefresh#85]
Site https://registry.terraform.io/providers/codefresh-io/codefresh/latest/docs no mention of Data Source

In addition, it would be interesting to expand the Data Source

Example create a data source for codefresh_project (currently even in the docs a "go horse" with variables is used)
Example.
data.codefresh_project.test.name

**Comment by brunotorrente** [comment]
Doc that can be inserted
Source:  https://github.com/codefresh-io/terraform-provider-codefresh/tree/master/docs/data

**Comment by korenyoni** [comment]
Thanks for submitting this issue. I'm going to try and fit this into a minor release (`0.1.0`) that is planned in the next two weeks.

**Comment by korenyoni** [comment]
Resolved in `0.3.0` via https://github.com/codefresh-io/terraform-provider-codefresh/pull/104
