### ISSUE TITLE
New Datasources: Pipeline/Projects

### ISSUE THREAD

**Issue by brunotorrente** [codefresh-io/terraform-provider-codefresh#87]
The suggestion is to include two new datasources,

codefresh_pipeline (returns the complete data for a specific pipeline)

```
      data "codefresh_pipeline" "test" {
             name = "test"
       }
```

codefresh_pipelines (returns summaries of all pipelines)

```
      data "codefresh_pipelines" "list" {
             filter = { name : "^~ test" }
       }
```

**Comment by brunotorrente** [comment]
codefresh_projects (returns list of all projects)

```
      data "codefresh_projects" "list" {
             filter = { name : "^~ test" }
       }
```
codefresh_project (returns the complete data for a specific project)

data "codefresh_project" "test" {
             name = "test"
       }

**Comment by korenyoni** [comment]
Hi @brunotorrente,

Sorry for the delay. 

I started working on this, starting with Pipelines. Pipelines are a bit challenging because it's the most complicated schema. But I think you will see this in `0.4.0`.
