### ISSUE TITLE
Switch to semantic versions

### ISSUE THREAD

**Issue by dirien** [codefresh-io/terraform-provider-codefresh#88]
Hi,

It would be nice, if this repo would switch to semantic versions, so we can use this repo as go module -> https://go.dev/blog/publishing-go-modules

```
Every required module in a go.mod has a [semantic version](https://semver.org/), the minimum version of that dependency to use to build the module.

A semantic version has the form vMAJOR.MINOR.PATCH.
```

Currently, I get following error message:

```bash
go get github.com/codefresh-io/terraform-provider-codefresh@0.0.24
go: github.com/codefresh-io/terraform-provider-codefresh@v0.0.24: reading github.com/codefresh-io/terraform-provider-codefresh/go.mod at revision v0.0.24: unknown revision v0.0.24
```

**Comment by korenyoni** [comment]
Hi @dirien, I am currently looking at a larger release automation overhaul which addresses this also. See my personal fork: https://github.com/korenyoni/terraform-provider-codefresh/pull/1

I am discussing this internally with previous maintainers of this repo, and I will link a PR to this issue, alongside other issues.

**Comment by dirien** [comment]
Ah oky @korenyoni, than I should wait with the Pulumi provider, I started here -> https://github.com/dirien/pulumi-codefresh

Thanks for the feedback and letting me in the loop!
